---- Insérer de la donnée. ----
-- Table "Restaurants".
INSERT INTO Restaurants ("Name", "Planet", "Opening_year")
VALUES 	("Milky Way Diner", "Terre", 2467),
		("Cresheano", "Lunne", 2452),
		("MiamMiam", "Pluton", 2331),
		("SuperBon", "Soleil (5ème arrondisement)", 2477);

-- Table "Dishes".
INSERT INTO Dishes ("Name", "Price", "Category")
VALUES 	("Burger d’Astéroïde", 12.5, "Burgers"),
		("pizzas à l’antimatière douce", 5.31, "Pizza"),
		("pizza d’Astéroïde", 9.31, "pizza"),
		("pizza a la pizza", 12.5, "pizza"),
		("Burger à la pizza d’antimatière douce", 31, "Burgers"),
		("smoothies de nébuleuse", 2.60, "Smoothies"),
		("smoothies au choux fleur", 3, "Smoothies"),
		("smoothies à la pizza de burger", 11, "Smoothies"),
		("Quiche à la poussière d'étoile", 16, "Quiche"),
		("Quiche nature", 7, "Quiche"),
		("Quiche au caramel", 14.12, "Quiche");

-- Table "Employees".
INSERT INTO Employees ("Firstname", "Lastname", "Role", "IdRestaurant","hire_date")
VALUES 	("Zorglub", "Bidoum", "Chef cuisinier", 1, 2471),
		("Jannah", "Lefebvre", "plongeur", 2, 2453),
		("Lily", "Sanchez", "plongeur", 1, 2470),
		("Enzo", "Muller", "plongeur", 2, 2468),
		("Loan", "Roussel", "plongeur", 3, 2413),
		("Zoé", "Fabre", "plongeur", 4, 2479),
		("Apolline", "Blanc", "plongeur", 1, 2483),
		("Eva", "Bertrand", "plongeur", 1, 2480),
		("Arthur", "Guerin", "plongeur", 1, 2476),
		("Suzanne", "Roche", "plongeur", 4, 2482),
		("Inaya", "Petit", "plongeur", 1, 2473),
		("Gaspard", "Simon", "plongeur", 4, 2486),
		("Théo", "Moreau", "plongeur", 4, 2485),
		("Yasmine", "Morin", "commis de cuisine", 3, 2400),
		("Adèle", "Arnaud", "commis de cuisine", 1, 2468),
		("Soan", "Lecomte", "commis de cuisine", 3, 2431),
		("Nathan", "Masson", "commis de cuisine", 3, 2420),
		("Margot", "Mercier", "cuisinier", 2, 2452),
		("Victor", "Fontaine", "cuisinier", 2, 2456),
		("Auguste", "Boyer", "cuisinier", 2, 2468),
		("Roméo", "Meunier", "cuisinier", 2, 2453),
		("Yanis", "Renard", "cuisinier", 1, 2469),
		("Roméo", "Garcia", "cuisinier", 1, 2470),
		("Alexandre", "Sanchez", "cuisinier", 3, 2401),
		("Zayn", "Olivier", "cuisinier", 3, 2420),
		("Léonie", "Thomas", "serveur", 3, 2423),
		("Marie", "Richard", "serveur", 3, 2413),
		("Joséphine", "Boyer", "serveur", 3, 2479),
		("Noah", "Philippe", "serveur", 4, 2477),
		("Zayn", "Martinez", "serveur", 4, 2482),
		("Louna", "Leroy", "serveur", 4, 2479),
		("Marin", "Renard", "serveur", 4, 2483),
		("Lana", "Robert", "serveur", 4, 2486),
		("Mathis", "Vidal", "serveur", 4, 2486),
		("Enzo", "Martinez", "serveur", 1, 2481),
		("Marceau", "Noel", "serveur", 1, 2483),
		("Chloé", "Roux", "chef cuisinier", 1, 2482),
		("Eden", "Roche", "chef cuisinier", 1, 2486),
		("Camille", "Robert", "chef cuisinier", 3, 2416),
		("Gabin", "Lopez", "chef cuisinier", 3, 2453),
		("Théo", "Durand", "chef cuisinier", 2, 2458),
		("Julia", "Payet", "chef cuisinier", 1, 2476);
